/*
 * File: app/model/Visita.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AritmiaRef.model.Visita', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Boolean',
        'Ext.data.field.Number',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json',
        'Ext.data.identifier.Uuid'
    ],

    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            type: 'date',
            name: 'dataVisita',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'visitaPappone'
        },
        {
            type: 'int',
            name: 'provenienzaFk'
        },
        {
            type: 'string',
            name: 'provenienza'
        },
        {
            type: 'string',
            name: 'ecoCardiografia'
        },
        {
            type: 'string',
            name: 'ecg'
        },
        {
            type: 'int',
            name: 'pazienteFk'
        },
        {
            type: 'string',
            name: 'paziente'
        },
        {
            type: 'string',
            name: 'terapiaInCorso'
        },
        {
            type: 'int',
            name: 'eta'
        },
        {
            type: 'int',
            name: 'operatoreSanitarioFk'
        },
        {
            type: 'string',
            name: 'operatoreSanitario'
        },
        {
            type: 'date',
            name: 'dataEsami',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'glicemia'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'terapiaInAtto'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'azotemia'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'creatinina'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'acidoUrico'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'transaminasiGO'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'transaminasiGP'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'fosfatasiAlcalica'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ggt'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'cpk'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'cpkmB'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ldh'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'bilirubinaTotale'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'bilirubinaDiretta'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'colesteroloTotale'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'colesteroloHDL'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'colesteroloLDL'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'trigliceridi'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'potassio'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'magnesio'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'pt'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ves'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'hbsAg'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ft3'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ft4'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'cloro'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'elettroforesiProteica'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'ptt'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'vdrl'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'hvc'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'tsh'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'sodio'
        },
        {
            type: 'float',
            allowNull: true,
            defaultValue: null,
            name: 'calcio'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'emocromo'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'fibrinogeno'
        },
        {
            type: 'string',
            name: 'altriEsamiEmatochimici'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'frequenzaBasale'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'paBasaleSistolica'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'paBasaleDiastolica'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'peso'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'altezza'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'superficieCorporea'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'esameObiettivo'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'giudizioClinico'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'terapiaConsigliata'
        },
        {
            type: 'string',
            name: 'relazioneProceduraPappone'
        },
        {
            type: 'string',
            name: 'conclusioniVisitaPappone'
        },
        {
            type: 'string',
            name: 'testoVisitaPappone'
        },
        {
            type: 'string',
            name: 'MyString39'
        },
        {
            type: 'int',
            name: 'ambulatorioFk'
        },
        {
            type: 'string',
            name: 'ambulatorio'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/visite',
        reader: {
            type: 'json'
        },
        writer: {
            type: 'json',
            writeAllFields: true
        }
    },

    identifier: {
        type: 'uuid'
    }
});