/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Prestazione',
        'Operatore',
        'OperatoreJoined',
        'PrestazioneJoined',
        'Role',
        'Visita'
    ],
    stores: [
        'Prestazioni',
        'Operatori',
        'OperatoriJoined',
        'PrestazioniJoined',
        'Visite',
        'Roles'
    ],
    views: [
        'MainView',
        'prestazione.PrestazioneWindow',
        'visita.Visita',
        'visita.Visite',
        'operatore.OperatoreWindow',
        'operatore.OperatoreForm',
        'prestazione.Prestazione'
    ],
    controllers: [
        'Navigation'
    ],
    name: 'AritmiaRef',

    launch: function() {
        Ext.create('AritmiaRef.view.MainView');
    }

});
