/*
 * File: app/view/visita/Visita.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AritmiaRef.view.visita.Visita', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.visita.visita',

    requires: [
        'AritmiaRef.view.visita.VisitaViewModel',
        'AritmiaRef.view.visita.VisitaViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Number',
        'Ext.menu.Menu',
        'Ext.menu.Separator',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.selection.CheckboxModel'
    ],

    controller: 'visita.visita',
    viewModel: {
        type: 'visita.visita'
    },
    itemId: 'visitaPanel',
    title: 'Visita',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            flex: 3,
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        },
        {
            xtype: 'container',
            flex: 20,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 5,
                    border: true,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Dati Generali',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Dati generali visita',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Data visita:'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Visita prof. Pappone:'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    anchor: '100%',
                                                    fieldLabel: 'Provenienza:',
                                                    store: [
                                                        'Pronto soccorso',
                                                        'Cardiochirurgia',
                                                        'Aritmologia',
                                                        'Altro reparto'
                                                    ]
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Palermo:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Ecocardiografia:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'ECG:'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Stampa l\'appuntamento'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Esami ematochimici',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            padding: '0 5 0 0 ',
                                            title: 'Esami ematochimici',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'table',
                                                        columns: 3
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'datefield',
                                                            width: '100%',
                                                            fieldLabel: 'Data esami:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Glicemia:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Azotemia:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Creatinina:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Acido urico:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Transaminasi GO:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Transaminasi GP:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Fosfatasi alcalica:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'GGT:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'CPK:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'CPK -mB:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'LDH:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Bilirubina totale:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Bilirubina diretta:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo totale:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo HDL'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo LDL:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Trigliceridi:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Potassio:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Magnesio:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'P.T.:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'VES:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'HbsAg:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'FT3:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'FT4:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Cloro:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: 100,
                                                            fieldLabel: 'Elettroforesi proteica:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'P.T.T.:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'VDRL:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'HVC:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'TSH:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Sodio:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Calcio:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Emocromo:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Fibrinogeno:'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Esame urine:'
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            colspan: 3,
                                                            anchor: '100%',
                                                            minHeight: 120,
                                                            width: '100%',
                                                            fieldLabel: 'Altri esami ematochimici:'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Dati Paziente',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Dati paziente',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Frequenza basale:'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'P.A. basale sistolica:'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'P.A. basale diastolica:'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Peso:'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Altezza'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Superfice corporea',
                                                    readOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Conclusioni',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Conclusioni',
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Esame Obiettivo:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Giudizio clinico:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Terapia consigliata:'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Visita prof. Pappone',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Visita prof. Pappone',
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Relazione procedura:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Conclusioni:'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Visita:'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    title: 'Riferimenti',
                    items: [
                        {
                            xtype: 'menu',
                            flex: 1,
                            floating: false,
                            margin: '40 10 10 10',
                            width: '100%',
                            bodyPadding: '20 5 5 5',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Paziente'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Anamnesi'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Referto'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Appuntamento'
                                },
                                {
                                    xtype: 'menuseparator',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Holter'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Head-up Tilt Test'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Genetica'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Ergonometrico'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Ecocardiografia'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            flex: 10,
            bodyPadding: '0 0 10 0',
            activeTab: 0,
            minTabWidth: 200,
            items: [
                {
                    xtype: 'gridpanel',
                    reference: 'operatoriGrid',
                    title: 'Operatori sanitari',
                    autoLoad: true,
                    store: 'OperatoriJoined',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 5,
                            dataIndex: 'firstName',
                            text: 'Nome'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 5,
                            dataIndex: 'lastName',
                            text: 'Cognome'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 4,
                            dataIndex: 'roleDescription',
                            text: 'Ruolo'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'phone',
                            text: 'Telefono'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'email',
                            text: 'Email'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'idNumber',
                            text: 'Numero identificativo'
                        },
                        {
                            xtype: 'actioncolumn',
                            flex: 1,
                            width: 40,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        const win = new AritmiaRef.view.operatore.OperatoreWindow();
                                        const viewModel=win.down('form').getViewModel();
                                        viewModel.set('recordOperatore',record);
                                        viewModel.set('storeOperatoriJoined',view.getStore());
                                        viewModel.set('indexOfRecordInsertion',rowIndex);
                                        win.show();
                                    },
                                    iconCls: 'x-fa fa-pen'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Aggiungi operatore',
                                    listeners: {
                                        click: 'onAddOperatoreButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancella operatori selezionati',
                                    listeners: {
                                        click: 'onRemoveOperatoriButtonClick'
                                    }
                                }
                            ]
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel',
                        checkOnly: true
                    },
                    tabConfig: {
                        xtype: 'tab',
                        dock: 'left',
                        width: 100
                    }
                },
                {
                    xtype: 'gridpanel',
                    reference: 'prestazioniGrid',
                    title: 'Prestazioni',
                    autoLoad: true,
                    store: 'PrestazioniJoined',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'id',
                            text: 'Codice prestazione'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 10,
                            dataIndex: 'description',
                            text: 'Descrizione'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 40,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        const win = new AritmiaRef.view.prestazione.PrestazioneWindow();
                                        const viewModel=win.down('form').getViewModel();
                                        viewModel.set('recordPrestazione',record);
                                        viewModel.set('storePrestazioniJoined',view.getStore());
                                        viewModel.set('indexOfRecordInsertion',rowIndex);
                                        win.show();

                                    },
                                    iconCls: 'x-fa fa-pen',
                                    tooltip: 'Edit'
                                }
                            ]
                        }
                    ],
                    tabConfig: {
                        xtype: 'tab',
                        dock: 'left',
                        width: 100
                    },
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Aggiungi prestazione',
                                    listeners: {
                                        click: 'onAddPrestazioneButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancella prestazioni selezionate',
                                    listeners: {
                                        click: 'onRemovePrestazioniButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});