/*
 * File: app/view/visita/Visita.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AritmiaRef.view.visita.Visita', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.visita.visita',

    requires: [
        'AritmiaRef.view.visita.VisitaViewModel',
        'AritmiaRef.view.visita.VisitaViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.field.TextArea',
        'Ext.menu.Menu',
        'Ext.menu.Separator',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel'
    ],

    controller: 'visita.visita',
    viewModel: {
        type: 'visita.visita'
    },
    itemId: 'visitaPanel',
    title: 'Visita',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            fieldDefaults: {
                labelWidth: 160,
                labelAlign: 'right',
                selectOnFocus: true
            },
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Paziente e medico',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        padding: '0 0 10 0'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 3,
                                    fieldLabel: 'Paziente',
                                    name: 'pazienteFk',
                                    allowBlank: false,
                                    autoLoadOnValue: true,
                                    displayField: 'fullName',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'Pazienti',
                                    typeAhead: true,
                                    valueField: 'id',
                                    bind: {
                                        value: '{visitaRecord.pazienteFk}'
                                    },
                                    listeners: {
                                        select: 'onPazienteComboboSelect'
                                    },
                                    listConfig: {
                                        xtype: 'boundlist',
                                        itemSelector: 'div',
                                        itemTpl: [
                                            '{lastName} {firstName}'
                                        ]
                                    }
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    fieldLabel: 'Data visita:',
                                    format: 'd/m/Y',
                                    bind: {
                                        value: '{visitaRecord.dataVisita}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 3,
                                    fieldLabel: 'Medico di riferimento:',
                                    name: 'operatoreFk',
                                    allowBlank: false,
                                    autoLoadOnValue: true,
                                    autoSelect: false,
                                    autoSelectLast: false,
                                    displayField: 'fullName',
                                    queryMode: 'local',
                                    store: 'Operatori',
                                    typeAhead: true,
                                    valueField: 'id',
                                    bind: {
                                        value: '{visitaRecord.operatoreFk}'
                                    },
                                    listeners: {
                                        select: 'onOperatoreComboboxSelect'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    flex: 1,
                                    fieldLabel: 'Età',
                                    bind: {
                                        value: '{visitaRecord.eta}'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 5,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 5,
                    border: true,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Dati Generali',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Dati generali visita',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Data visita:',
                                                    format: 'd/m/Y',
                                                    bind: {
                                                        value: '{visitaRecord.dataVisita}'
                                                    }
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Visita prof. Pappone:',
                                                    bind: {
                                                        value: '{visitaRecord.visitaPappone}'
                                                    }
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    anchor: '100%',
                                                    fieldLabel: 'Provenienza:',
                                                    name: 'provenienzaFk',
                                                    displayField: 'descrizione',
                                                    queryMode: 'local',
                                                    store: 'Provenienze',
                                                    typeAhead: true,
                                                    valueField: 'id',
                                                    bind: {
                                                        value: '{visitaRecord.provevienzaFk}'
                                                    },
                                                    listeners: {
                                                        select: 'onProvenienzaComboboxSelect'
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Terapia in corso',
                                                    bind: {
                                                        value: '{visitaRecord.terapiaInCorso}'
                                                    }
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Palermo:',
                                                    bind: {
                                                        value: '{visitaRecord.palermo}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'Ecocardiografia:',
                                                    bind: {
                                                        value: '{visitaRecord.ecoCardiografia}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 120,
                                                    fieldLabel: 'ECG:',
                                                    bind: {
                                                        value: '{visitaRecord.ecg}'
                                                    }
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Stampa l\'appuntamento',
                                                    bind: {
                                                        value: '{visitaRecord.stampaAppuntamento}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Esami ematochimici',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            padding: '0 5 0 0 ',
                                            title: 'Esami ematochimici',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'table',
                                                        columns: 3
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'datefield',
                                                            width: '100%',
                                                            fieldLabel: 'Data esami:',
                                                            bind: {
                                                                value: '{visitaRecord.dataEsami}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Glicemia:',
                                                            bind: {
                                                                value: '{visitaRecord.glicemia}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Azotemia:',
                                                            bind: {
                                                                value: '{visitaRecord.azotemia}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Creatinina:',
                                                            bind: {
                                                                value: '{visitaRecord.creatinina}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Acido urico:',
                                                            bind: {
                                                                value: '{visitaRecord.acidoUrico}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Transaminasi GO:',
                                                            bind: {
                                                                value: '{visitaRecord.transaminasiGO}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Transaminasi GP:',
                                                            bind: {
                                                                value: '{visitaRecord.transaminasiGP}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Fosfatasi alcalica:',
                                                            bind: {
                                                                value: '{visitaRecord.fosfatasiAlcalica}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'GGT:',
                                                            bind: {
                                                                value: '{visitaRecord.ggt}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'CPK:',
                                                            bind: {
                                                                value: '{visitaRecord.cpk}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'CPK -mB:',
                                                            bind: {
                                                                value: '{visitaRecord.cpkmB}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'LDH:',
                                                            bind: {
                                                                value: '{visitaRecord.ldh}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Bilirubina totale:',
                                                            bind: {
                                                                value: '{visitaRecord.bilirubinaTotale}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Bilirubina diretta:',
                                                            bind: {
                                                                value: '{visitaRecord.bilirubinaDiretta}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo totale:',
                                                            bind: {
                                                                value: '{visitaRecord.colesteroloTotale}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo HDL',
                                                            bind: {
                                                                value: '{visitaRecord.colesteroloHDL}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Colesterolo LDL:',
                                                            bind: {
                                                                value: '{visitaRecord.colesteroloLDL}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Trigliceridi:',
                                                            bind: {
                                                                value: '{visitaRecord.trigliceridi}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Potassio:',
                                                            bind: {
                                                                value: '{visitaRecord.potassio}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Magnesio:',
                                                            bind: {
                                                                value: '{visitaRecord.magnesio}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'P.T.:',
                                                            bind: {
                                                                value: '{visitaRecord.pt}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'VES:',
                                                            bind: {
                                                                value: '{visitaRecord.ves}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'HbsAg:',
                                                            bind: {
                                                                value: '{visitaRecord.hbsAg}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'FT3:',
                                                            bind: {
                                                                value: '{visitaRecord.ft3}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'FT4:',
                                                            bind: {
                                                                value: '{visitaRecord.ft4}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Cloro:',
                                                            bind: {
                                                                value: '{visitaRecord.cloro}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Elettroforesi proteica:',
                                                            bind: {
                                                                value: '{visitaRecord.elettroforesiProteica}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'P.T.T.:',
                                                            bind: {
                                                                value: '{visitaRecord.ptt}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'VDRL:',
                                                            bind: {
                                                                value: '{visitaRecord.vdrl}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'HVC:',
                                                            bind: {
                                                                value: '{visitaRecord.hvc}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'TSH:',
                                                            bind: {
                                                                value: '{visitaRecord.tsh}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Sodio:',
                                                            bind: {
                                                                value: '{visitaRecord.sodio}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Calcio:',
                                                            bind: {
                                                                value: '{visitaRecord.calcio}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Emocromo:',
                                                            bind: {
                                                                value: '{visitaRecord.emocromo}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Fibrinogeno:',
                                                            bind: {
                                                                value: '{visitaRecord.fibrinogeno}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            width: '100%',
                                                            fieldLabel: 'Esame urine:',
                                                            bind: {
                                                                value: '{visitaRecord.esameUrine}'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'toolbar',
                                                            colspan: 3,
                                                            items: [
                                                                {
                                                                    xtype: 'tbfill'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    text: 'Testi standard'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            colspan: 3,
                                                            anchor: '100%',
                                                            minHeight: 90,
                                                            width: '100%',
                                                            fieldLabel: 'Altri esami ematochimici:',
                                                            bind: {
                                                                value: '{visitaRecord.altriEsamiEmatochimici}'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Dati Paziente',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Dati paziente',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Frequenza basale:',
                                                    bind: {
                                                        value: '{visitaRecord.frequenzaBasale}'
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'P.A. basale sistolica:',
                                                    bind: {
                                                        value: '{visitaRecord.paBasaleSistolica}'
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'P.A. basale diastolica:',
                                                    bind: {
                                                        value: '{visitaRecord.paBasaleDiastolica}'
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Peso:',
                                                    bind: {
                                                        value: '{visitaRecord.peso}'
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Altezza',
                                                    bind: {
                                                        value: '{visitaRecord.altezza}'
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Superfice corporea',
                                                    readOnly: true,
                                                    bind: {
                                                        value: '{visitaRecord.superficieCorporea}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Conclusioni',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Conclusioni',
                                            items: [
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Esame Obiettivo:',
                                                    bind: {
                                                        value: '{visitaRecord.esameObiettivo}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Giudizio clinico:',
                                                    bind: {
                                                        value: '{visitaRecord.giudizioClinico}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Terapia consigliata:',
                                                    bind: {
                                                        value: '{visitaRecord.terapiaConsigliata}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Visita prof. Pappone',
                            tabConfig: {
                                xtype: 'tab',
                                bind: {
                                    hidden: '{!visitaRecord.visitaPappone}'
                                }
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        labelWidth: 160,
                                        labelAlign: 'right',
                                        selectOnFocus: true
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Visita prof. Pappone',
                                            items: [
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Relazione procedura:',
                                                    bind: {
                                                        value: '{visitaRecord.relazioneProceduraPappone}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Conclusioni:',
                                                    bind: {
                                                        value: '{visitaRecord.conclusioniVisitaPappone}'
                                                    }
                                                },
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Testi standard'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    anchor: '100%',
                                                    minHeight: 100,
                                                    fieldLabel: 'Visita:',
                                                    bind: {
                                                        value: '{visitaRecord.testoVisitaPappone}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Esci',
                                    listeners: {
                                        click: 'onEsciButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Salva e torna ala lista',
                                    listeners: {
                                        click: 'onSalvaEdEsciButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'Salva e procedi'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    border: true,
                    title: 'Riferimenti',
                    items: [
                        {
                            xtype: 'menu',
                            flex: 1,
                            floating: false,
                            margin: '',
                            width: '100%',
                            bodyPadding: '20 5 5 5',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Paziente'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Anamnesi'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Referto'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Appuntamento'
                                },
                                {
                                    xtype: 'menuseparator',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Holter'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Head-up Tilt Test'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Genetica'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Ergonometrico'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Ecocardiografia'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            flex: 2,
            height: 100,
            bodyPadding: '0 0 10 0',
            activeTab: 0,
            minTabWidth: 200,
            items: [
                {
                    xtype: 'gridpanel',
                    reference: 'operatoriGrid',
                    title: 'Operatori sanitari',
                    autoLoad: true,
                    store: 'OperatoriJoined',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 5,
                            dataIndex: 'firstName',
                            text: 'Nome'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 5,
                            dataIndex: 'lastName',
                            text: 'Cognome'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 4,
                            dataIndex: 'roleDescription',
                            text: 'Ruolo'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'phone',
                            text: 'Telefono'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'email',
                            text: 'Email'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 3,
                            dataIndex: 'idNumber',
                            text: 'Numero identificativo'
                        },
                        {
                            xtype: 'actioncolumn',
                            flex: 1,
                            width: 40,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        const win = new AritmiaRef.view.operatore.OperatoreWindow();
                                        const viewModel=win.down('form').getViewModel();
                                        viewModel.set('recordOperatore',record);
                                        viewModel.set('storeOperatoriJoined',view.getStore());
                                        viewModel.set('indexOfRecordInsertion',rowIndex);
                                        win.show();
                                    },
                                    iconCls: 'x-fa fa-pen'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Aggiungi operatore',
                                    listeners: {
                                        click: 'onAddOperatoreButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancella operatori selezionati',
                                    listeners: {
                                        click: 'onRemoveOperatoriButtonClick'
                                    }
                                }
                            ]
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel',
                        checkOnly: true
                    },
                    tabConfig: {
                        xtype: 'tab',
                        dock: 'left',
                        width: 100
                    }
                },
                {
                    xtype: 'gridpanel',
                    reference: 'prestazioniGrid',
                    title: 'Prestazioni',
                    autoLoad: true,
                    store: 'PrestazioniJoined',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'code',
                            text: 'Codice prestazione'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 10,
                            dataIndex: 'description',
                            text: 'Descrizione'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 40,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        const win = new AritmiaRef.view.prestazione.PrestazioneWindow();
                                        const viewModel=win.down('form').getViewModel();
                                        viewModel.set('recordPrestazione',record);
                                        viewModel.set('storePrestazioniJoined',view.getStore());
                                        viewModel.set('indexOfRecordInsertion',rowIndex);
                                        win.show();

                                    },
                                    iconCls: 'x-fa fa-pen',
                                    tooltip: 'Edit'
                                }
                            ]
                        }
                    ],
                    tabConfig: {
                        xtype: 'tab',
                        dock: 'left',
                        width: 100
                    },
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Aggiungi prestazione',
                                    listeners: {
                                        click: 'onAddPrestazioneButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancella prestazioni selezionate',
                                    listeners: {
                                        click: 'onRemovePrestazioniButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});