/*
 * File: app/view/prestazione/PrestazioneWindow.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AritmiaRef.view.prestazione.PrestazioneWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.prestazione.prestazionewindow',

    requires: [
        'AritmiaRef.view.prestazione.PrestazioneWindowViewModel',
        'AritmiaRef.view.prestazione.Prestazione',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'prestazione.prestazionewindow'
    },
    modal: true,
    height: 431,
    width: 800,
    title: 'Prestazione',

    items: [
        {
            xtype: 'prestazione.prestazione'
        }
    ]

});